<?php

require_once __DIR__ . '/config.php';

require_login();

$role = $_SESSION['role'] ?? '';

$isAdmin = strcasecmp(
    $role,
    'Administrator'
) === 0;


/*
|--------------------------------------------------------------------------
| JSON ERROR RESPONSE
|--------------------------------------------------------------------------
*/

function backupError($message, $status = 400)
{
    /*
     * If an error happens before the download starts,
     * return JSON so the JavaScript can display the error
     * inside the modal instead of closing the page.
     */

    http_response_code($status);

    header(
        'Content-Type: application/json; charset=utf-8'
    );

    echo json_encode([
        'success' => false,
        'message' => $message
    ]);

    exit;
}


/*
|--------------------------------------------------------------------------
| CHECK ADMIN PERMISSION
|--------------------------------------------------------------------------
*/

if (!$isAdmin) {

    backupError(
        'Administrator access required.',
        403
    );
}


/*
|--------------------------------------------------------------------------
| CHECK PASSWORD
|--------------------------------------------------------------------------
*/

$password = $_POST['password'] ?? '';

if ($password === '') {

    backupError(
        'Password is required.'
    );
}


/*
|--------------------------------------------------------------------------
| VERIFY ADMIN PASSWORD
|--------------------------------------------------------------------------
*/

try {

    $stmt = $pdo->prepare("
        SELECT password
        FROM users
        WHERE id = ?
        LIMIT 1
    ");

    $stmt->execute([
        (int)($_SESSION['user_id'] ?? 0)
    ]);

    $user = $stmt->fetch(PDO::FETCH_ASSOC);

} catch (Throwable $e) {

    backupError(
        'Unable to verify administrator password.',
        500
    );
}


if (
    !$user ||
    empty($user['password']) ||
    !password_verify(
        $password,
        $user['password']
    )
) {

    backupError(
        'Incorrect password. Backup cancelled.'
    );
}


/*
|--------------------------------------------------------------------------
| GET ALL TABLES
|--------------------------------------------------------------------------
*/

try {

    $tables = $pdo
        ->query("SHOW TABLES")
        ->fetchAll(PDO::FETCH_COLUMN);

} catch (Throwable $e) {

    backupError(
        'Unable to retrieve database tables.',
        500
    );
}


/*
|--------------------------------------------------------------------------
| START SQL BACKUP
|--------------------------------------------------------------------------
*/

$sql = '';

$sql .=
    "-- School Data Management System Backup\n";

$sql .=
    "-- Generated: " .
    date('Y-m-d H:i:s') .
    "\n\n";

$sql .=
    "-- Database backup generated by the School Data Management System.\n";

$sql .=
    "-- This file contains table structures and table data.\n\n";

$sql .=
    "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n";

$sql .=
    "SET AUTOCOMMIT = 0;\n";

$sql .=
    "START TRANSACTION;\n";

$sql .=
    "SET time_zone = \"+00:00\";\n\n";

$sql .=
    "SET FOREIGN_KEY_CHECKS=0;\n\n";


/*
|--------------------------------------------------------------------------
| EXPORT EACH TABLE
|--------------------------------------------------------------------------
*/

foreach ($tables as $table) {

    /*
     * Escape table name safely for SQL identifier usage.
     */

    $safeTable = str_replace(
        '`',
        '``',
        $table
    );


    /*
     |--------------------------------------------------------------------------
     | TABLE HEADER
     |--------------------------------------------------------------------------
     */

    $sql .=
        "-- --------------------------------------------------------\n";

    $sql .=
        "-- Table structure for table `" .
        $safeTable .
        "`\n";

    $sql .=
        "-- --------------------------------------------------------\n\n";


    /*
     |--------------------------------------------------------------------------
     | DROP EXISTING TABLE
     |--------------------------------------------------------------------------
     */

    $sql .=
        "DROP TABLE IF EXISTS `" .
        $safeTable .
        "`;\n\n";


    /*
     |--------------------------------------------------------------------------
     | GET CREATE TABLE STATEMENT
     |--------------------------------------------------------------------------
     */

    try {

        $createStmt = $pdo->query(
            "SHOW CREATE TABLE `" .
            $safeTable .
            "`"
        );

        $createRow =
            $createStmt->fetch(PDO::FETCH_ASSOC);

    } catch (Throwable $e) {

        backupError(
            'Unable to export table structure for ' .
            $table . '.',
            500
        );
    }


    if (!$createRow) {

        backupError(
            'Unable to read table structure for ' .
            $table . '.',
            500
        );
    }


    /*
     * SHOW CREATE TABLE normally returns:
     *
     * Table
     * Create Table
     *
     * But use the second value so this also works
     * if the table name has unusual capitalization.
     */

    $createSql = '';

    foreach ($createRow as $key => $value) {

        if (
            stripos(
                $key,
                'Create Table'
            ) !== false
        ) {

            $createSql = $value;

            break;
        }
    }


    /*
     * Fallback in case MySQL uses a slightly different key.
     */

    if ($createSql === '') {

        $values = array_values($createRow);

        $createSql =
            $values[1] ??
            '';
    }


    if ($createSql === '') {

        backupError(
            'Unable to generate CREATE TABLE statement for ' .
            $table . '.',
            500
        );
    }


    $sql .=
        $createSql .
        ";\n\n";


    /*
     |--------------------------------------------------------------------------
     | GET TABLE DATA
     |--------------------------------------------------------------------------
     */

    $sql .=
        "-- --------------------------------------------------------\n";

    $sql .=
        "-- Dumping data for table `" .
        $safeTable .
        "`\n";

    $sql .=
        "-- --------------------------------------------------------\n\n";


    try {

        $dataStmt = $pdo->query(
            "SELECT * FROM `" .
            $safeTable .
            "`"
        );

        $rows =
            $dataStmt->fetchAll(
                PDO::FETCH_ASSOC
            );

    } catch (Throwable $e) {

        backupError(
            'Unable to export data from table ' .
            $table . '.',
            500
        );
    }


    /*
     |--------------------------------------------------------------------------
     | INSERT DATA
     |--------------------------------------------------------------------------
     */

    if (!empty($rows)) {

        /*
         * Get column names from the first row.
         */

        $columns =
            array_keys(
                $rows[0]
            );


        $columnSql = [];


        foreach ($columns as $column) {

            $columnSql[] =
                '`' .
                str_replace(
                    '`',
                    '``',
                    $column
                ) .
                '`';
        }


        $columnSql =
            implode(
                ', ',
                $columnSql
            );


        /*
         * Insert rows one by one.
         *
         * This is slightly larger than combining
         * everything into one INSERT, but it makes
         * the backup much more reliable for larger
         * school databases.
         */

        foreach ($rows as $row) {

            $values = [];


            foreach ($columns as $column) {

                $value =
                    $row[$column];


                if ($value === null) {

                    $values[] =
                        'NULL';

                } else {

                    $values[] =
                        $pdo->quote(
                            (string)$value
                        );
                }
            }


            $sql .=
                "INSERT INTO `" .
                $safeTable .
                "` (" .
                $columnSql .
                ") VALUES (" .
                implode(
                    ', ',
                    $values
                ) .
                ");\n";
        }


        $sql .= "\n";

    } else {

        $sql .=
            "-- No data found in this table.\n\n";
    }
}


/*
|--------------------------------------------------------------------------
| RESTORE FOREIGN KEY CHECKS
|--------------------------------------------------------------------------
*/

$sql .=
    "SET FOREIGN_KEY_CHECKS=1;\n\n";

$sql .=
    "COMMIT;\n";


/*
|--------------------------------------------------------------------------
| GENERATE FILE NAME
|--------------------------------------------------------------------------
*/

$filename =
    'school_data_backup_' .
    date('Y-m-d_H-i-s') .
    '.sql';


/*
|--------------------------------------------------------------------------
| DOWNLOAD HEADERS
|--------------------------------------------------------------------------
*/

header(
    'Content-Type: application/sql; charset=utf-8'
);

header(
    'Content-Disposition: attachment; filename="' .
    $filename .
    '"'
);

header(
    'Content-Length: ' .
    strlen($sql)
);

header(
    'Cache-Control: no-store, no-cache, must-revalidate'
);

header(
    'Pragma: no-cache'
);


/*
|--------------------------------------------------------------------------
| OUTPUT BACKUP
|--------------------------------------------------------------------------
*/

echo $sql;

exit;